project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "John Robin Inston"
  navbar:
    right:
      - about.qmd
      - icon: youtube
        href: https://www.youtube.com/@JohnRobinInston
      - icon: github
        href: https://github.com/johnrobininston
      - icon: linkedin
        href: https://www.linkedin.com/in/johninston/
      - icon: twitter-x
        href: https://x.com/John_Inston
  page-footer: "Copyright 2026, John Inston."
  back-to-top-navigation: true
format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css



